const { contextBridge, ipcRenderer } = require('electron');

// NOTE: this preload runs with sandbox:true (main window webPreferences), so
// it can ONLY require('electron') and Electron's own polyfilled built-ins —
// require()'ing another project file (e.g. './poke-formulas') throws and
// silently kills the WHOLE preload script before it ever reaches
// contextBridge.exposeInMainWorld('api', ...) below, leaving window.api
// undefined for everything (confirmed live: this broke basically the whole
// app, not just the one feature that used it). Poke-formulas math is
// computed in main.js instead (unsandboxed, requires it fine) and exposed
// through the pokeFormulas:* IPC channels below.

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('state:get'),
  getVersions: () => ({ app: '0.1.0', electron: process.versions.electron, chrome: process.versions.chrome }),
  addAccount: (payload) => ipcRenderer.invoke('accounts:add', payload),
  quickAddAccount: () => ipcRenderer.invoke('accounts:quickAdd'),
  removeAccount: (id) => ipcRenderer.invoke('accounts:remove', { id }),
  closeAllAccounts: () => ipcRenderer.invoke('accounts:closeAll'),
  closeAccount: (id) => ipcRenderer.invoke('accounts:closeOne', { id }),
  openAllAccounts: () => ipcRenderer.invoke('accounts:openAll'),
  activateAccount: (id) => ipcRenderer.invoke('accounts:activate', { id }),
  toggleMaximize: (id) => ipcRenderer.invoke('accounts:toggleMaximize', { id }),
  openInNewWindow: (id) => ipcRenderer.invoke('accounts:openInNewWindow', { id }),
  navigateAccount: (id, url) => ipcRenderer.invoke('account:navigate', { id, url }),
  setLayout: (mode) => ipcRenderer.invoke('layout:set', { mode }),
  reloadAccount: (id) => ipcRenderer.invoke('account:reload', { id }),
  reloadAccountHard: (id) => ipcRenderer.invoke('account:reloadHard', { id }),
  reopenLastClosed: () => ipcRenderer.invoke('accounts:reopenLastClosed'),
  findInPage: (id, text, opts) => ipcRenderer.send('account:findInPage', { id, text, ...opts }),
  stopFindInPage: (id) => ipcRenderer.send('account:stopFindInPage', { id }),
  onFindbarOpen: (cb) => ipcRenderer.on('findbar:open', (_e, data) => cb(data)),
  onFindbarClose: (cb) => ipcRenderer.on('findbar:close', (_e, data) => cb(data)),
  onFindbarResult: (cb) => ipcRenderer.on('findbar:result', (_e, data) => cb(data)),
  goBack: (id) => ipcRenderer.send('account:goBack', { id }),
  goForward: (id) => ipcRenderer.send('account:goForward', { id }),
  getMeta: () => ipcRenderer.invoke('app:getMeta'),
  getShortcuts: () => ipcRenderer.invoke('shortcuts:list'),
  onShortcutSelectPanel: (cb) => ipcRenderer.on('shortcut:selectPanel', (_e, data) => cb(data)),
  onShortcutNextPanel: (cb) => ipcRenderer.on('shortcut:nextPanel', () => cb()),
  onShortcutFocusAddress: (cb) => ipcRenderer.on('shortcut:focusAddress', () => cb()),
  onShortcutOpenSettings: (cb) => ipcRenderer.on('shortcut:openSettings', () => cb()),
  muteAccount: (id, muted) => ipcRenderer.invoke('account:mute', { id, muted }),
  addSpace: (payload) => ipcRenderer.invoke('spaces:add', payload),
  updateSpace: (id, fields) => ipcRenderer.invoke('spaces:update', { id, ...fields }),
  removeSpace: (id) => ipcRenderer.invoke('spaces:remove', { id }),
  activateSpace: (id) => ipcRenderer.invoke('spaces:activate', { id }),
  duplicateAccount: (id) => ipcRenderer.invoke('accounts:duplicate', { id }),
  updateAccount: (id, fields) => ipcRenderer.invoke('accounts:update', { id, ...fields }),
  reorderAccounts: (orderedIds) => ipcRenderer.invoke('accounts:reorder', orderedIds),
  reorderSpaces: (orderedIds) => ipcRenderer.invoke('spaces:reorder', orderedIds),
  clearSession: (id) => ipcRenderer.invoke('account:clearSession', { id }),
  showAccountMenu: (id) => ipcRenderer.send('accounts:contextmenu', { id }),
  showSpaceMenu: (id) => ipcRenderer.send('spaces:contextmenu', { id }),
  duplicateSpace: (id) => ipcRenderer.invoke('spaces:duplicate', { id }),
  setFreeRect: (id, rect) => ipcRenderer.invoke('account:setFreeRect', { id, rect }),
  setSplit: (ids, fracs, field) => ipcRenderer.invoke('layout:setSplit', { ids, fracs, field }),
  setLiveRect: (id, rect) => ipcRenderer.send('account:setLiveRect', { id, rect }),
  toggleSidebar: () => ipcRenderer.invoke('sidebar:toggle'),
  hideViews: () => ipcRenderer.send('ui:hide-views'),
  showViews: () => ipcRenderer.send('ui:show-views'),
  setZoom: (id, factor) => ipcRenderer.invoke('account:setZoom', { id, factor }),
  setZoomAll: (factor) => ipcRenderer.invoke('accounts:setZoomAll', { factor }),
  toggleFullscreen: () => ipcRenderer.send('app:toggleFullscreen'),
  relaunchApp: () => ipcRenderer.send('app:relaunch'),
  openDownloads: () => ipcRenderer.send('app:openDownloads'),
  openFileDownload: (id) => ipcRenderer.invoke('downloads:openFile', { id }),
  showDownloadInFolder: (id) => ipcRenderer.invoke('downloads:showInFolder', { id }),
  removeDownload: (id) => ipcRenderer.invoke('downloads:remove', { id }),
  clearDownloads: () => ipcRenderer.invoke('downloads:clear'),
  pauseDownload: (id) => ipcRenderer.invoke('downloads:pause', { id }),
  resumeDownload: (id) => ipcRenderer.invoke('downloads:resume', { id }),
  cancelDownload: (id) => ipcRenderer.invoke('downloads:cancel', { id }),
  muteAllAccounts: (muted) => ipcRenderer.invoke('accounts:muteAll', { muted }),
  updateSettings: (fields) => ipcRenderer.invoke('settings:update', fields),
  chooseDownloadsFolder: () => ipcRenderer.invoke('settings:chooseDownloadsFolder'),
  checkUpdates: () => ipcRenderer.invoke('settings:checkUpdates'),
  getPlugins: () => ipcRenderer.invoke('plugins:list'),
  addPassword: (entry) => ipcRenderer.invoke('passwords:add', entry),
  installUpdate: () => ipcRenderer.invoke('settings:installUpdate'),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (_e, data) => cb(data)),
  exportSpaces: () => ipcRenderer.invoke('settings:exportSpaces'),
  importSpaces: () => ipcRenderer.invoke('settings:importSpaces'),
  installExtensionFromStore: (input) => ipcRenderer.invoke('extensions:installFromStore', { input }),
  loadUnpackedExtension: () => ipcRenderer.invoke('extensions:loadUnpacked'),
  toggleExtension: (id, enabled) => ipcRenderer.invoke('extensions:toggle', { id, enabled }),
  removeExtension: (id) => ipcRenderer.invoke('extensions:remove', { id }),
  getMetrics: () => ipcRenderer.invoke('metrics:get'),
  getGameStats: () => ipcRenderer.invoke('gameStats:get'),
  getCreatureCatalog: () => ipcRenderer.invoke('pokeFormulas:getCreatureCatalog'),
  computeGrowthCalc: (payload) => ipcRenderer.invoke('pokeFormulas:computeGrowth', payload),
  addBookmark: (payload) => ipcRenderer.invoke('bookmarks:add', payload),
  removeBookmark: (id) => ipcRenderer.invoke('bookmarks:remove', { id }),
  exportBookmarks: () => ipcRenderer.invoke('bookmarks:export'),
  importBookmarks: () => ipcRenderer.invoke('bookmarks:import'),
  importPasswords: () => ipcRenderer.invoke('passwords:import'),
  removePassword: (id) => ipcRenderer.invoke('passwords:remove', { id }),
  getPasswords: () => ipcRenderer.invoke('passwords:list'),
  onStateUpdate: (cb) => ipcRenderer.on('state:update', (_e, data) => cb(data)),
  onNavUpdate: (cb) => ipcRenderer.on('nav:update', (_e, data) => cb(data)),
  onPanelsGeometry: (cb) => ipcRenderer.on('panels:geometry', (_e, data) => cb(data)),
  onOpenSpaceEditor: (cb) => ipcRenderer.on('ui:open-space-editor', (_e, data) => cb(data)),
  onOpenAccountEditor: (cb) => ipcRenderer.on('ui:open-account-editor', (_e, data) => cb(data))
});
